### PR TITLE
Dash Dev Tools

### PR DESCRIPTION
**Pull request by rmarren1**
Built on https://github.com/plotly/dash-renderer/pull/64.

### CODE REVIEW

**Comment by rmarren1** [comment]
Looks like this problem still remains...
> After investigating a bit more the input clear bug, it boils down to the way selenium clear the input. It doesn't send the onChange event for the cleared value so somehow the initial value get backs in. This is not something that would happen if the user cleared the input manually with backspaces or selecting the whole text and deleting. Thus, it is safe to patch the failing tests to fix that selenium bug.

**Comment by T4rk1n** [comment]
Yes it's still there, what is fixed is the callback counts, we need to modify the failing test.

**Comment by byronz** [comment]
@alexcjohnson  @Marc-Andre-Rivet would like to get some feedback on the last two fixes & improvement of unit tests:
1. [test initial state](https://github.com/plotly/dash-renderer/commit/a85afe6)
2. [test test_callbacks_generating_children](https://github.com/plotly/dash-renderer/commit/a51bf89)

it demonstrates the direction to make test case more concise and robust, but the current enhancements are still not ideal as the scope of each test is still big and lack of granularity.

**Comment by nicolaskruchten** [comment]
Let's remember to add some tests for the dev bundle :)

**Comment by nicolaskruchten** [comment]
possibly we should add some tests to the prod bundle that ensure that it's not "too big" ?

**Pull request merged**
