### PR TITLE
[WIP] Dash dev tools

### PR DESCRIPTION
**Pull request by rmarren1**
**Release Candidate**: `pip install dash-renderer==0.14.0rc7`
In this PR, we change the Dash app layout from something like:
```
<div id="react-entry-point">
  <div id="_dash-undo-redo">...</div>
  <div id="_dash-app-content">
    ...
    <SomeDashComponent />
    ...
  </div>
</div>
```
To the following
```
<div id="react-entry-point">
  <div id="_dash-undo-redo">...</div>
  <GlobalErrorContainer>
    <GlobalErrorOverlay>
      <div id="_dash-app-content">
        ...
        <ComponentErrorBoundary>
          <SomeDashComponent /> OR <ComponentErrorOverlay><SomeDashComponent /></ComponentErrorOverlay> OR <ComponentDisabledOverlay><SomeDashComponent /></ComponentDisabledOverlay>
        </ ComponentErrorBoundary>
        ...
      </div>
    </ GlobalErrorOverlay>
  </ GlobalErrorContainer>
</div>
```

The new components serve the following purposes:
* `GlobalErrorContainer` -- Container for the `GlobalErrorOverlay`, this component connects to the Redux store and passes state and functions down to the `GlobalErrorOverlay`, and also creates the Werkzueg error pop-up.
* `GlobalErrorOverlay` -- This component renders the main Dash app (`_dash-app-content`) along side a conditionally rendered 'error menu'.
* `ComponentErrorBoundary` -- This component wraps each Dash component in the `TreeContainer` and implements the `componentDidCatch` lifecycle method to catch errors in those Dash components. If there is an error in the component, a `ComponentErrorOverlay` component is displayed. If the component must be disabled (this component has a child in the callback graph that has an error) a `ComponentDisabledOverlay` component is displayed.

This PR also makes an update to the Redux store, adding an `error` state that looks like the following:
```
{
  ...,
  error : {
    frontEnd: [ { myUID: 'fjdsa89r32',
                       myID: 'button',
                       error: <javascript error object>,
                       info: <javascript info object> } ],
    backEnd: { errorPage: "...the html werkzueg page..."}
 }
  ...
}
```

### CODE REVIEW

**Comment by rmarren1** [comment]
Another pre-release at `dash-renderer==0.14.0-rc2` with
* Components covered in red when bugs are encountered, click on component to revert previous interaction and try again
* Werkzueg error pops out in a separate window and Dash app is covered in red, click button to revert previous interaction and try again

**Comment by rmarren1** [comment]
Yes I'll do that. Pretty sure that your error is because dash-table-experiments is written using in React 15 syntax, I think the only major difference is [here](https://github.com/plotly/dash-table-experiments/blob/1e5b24eec53627418c51027f561cb7bae591a95e/src/components/DataTable.react.js#L1) you would need to `import PropTypes from 'prop-types';` instead.

**Comment by T4rk1n** [comment]
That make senses.

**Comment by rmarren1** [comment]
`dash-renderer==0.14.0-rc3` is up with dev build and working unpkg link. Should be good as long as all components you are using support react 16 (so far this just means import PropTypes from 'prop-types')

**Comment by rmarren1** [comment]
Requires this PR: https://github.com/plotly/dash-renderer/pull/67

**Comment by rmarren1** [comment]
https://github.com/plotly/dash-dangerously-set-inner-html/issues/4

**Comment by rmarren1** [comment]
Just came across this: https://reactjs.org/blog/2017/09/08/dom-attributes-in-react-16.html

This would make for some annoying errors in tests that try to exactly match the rendered HTML to a string. I think this would affect `dash`, I'll look at the other repos aswell.

**Comment by valentijnnieman** [comment]
Hey @rmarren1 - I'm going to start on #94 soon, and was planning on creating a branch off of this branch. Should we fix the merge conflicts first, i.e. rebase, or is that too much work?

**Comment by rmarren1** [comment]
Continued in https://github.com/plotly/dash-renderer/pull/100

**Pull request closed without merging**
